services:
  claude-agent:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
      args:
        TZ: ${TZ:-America/New_York}
    container_name: ${INSTANCE_NAME:-claude-code-agent}
    ports:
      - "${EXTERNAL_PORT:-3010}:3000"
      - "${POSTGRES_PORT:-5432}:5432"
      - "${REDIS_PORT:-6379}:6379"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      # Isolated bind mounts per instance
      - ./volumes/${VOLUME_PREFIX:-claude-code-agent}/workspace:/workspace
      - ./volumes/${VOLUME_PREFIX:-claude-code-agent}/bashhistory:/commandhistory
      # Claude commands - read-only from source
      - ./.devcontainer/.claude/commands:/home/ubuntu/.claude/commands:ro
      - ./.devcontainer/.claude/README.md:/home/ubuntu/.claude/README.md:ro
      # Runtime data - isolated per instance
      - ./volumes/${VOLUME_PREFIX:-claude-code-agent}/config:/home/ubuntu/.claude/runtime
    working_dir: /workspace
    user: ubuntu
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096
      - CLAUDE_CONFIG_DIR=/home/ubuntu/.claude
      - POWERLEVEL9K_DISABLE_GITSTATUS=true
      # GitHub authentication token for Git and CLI (set via .env file or environment)
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
    command: bash
    stdin_open: true
    tty: true
    restart: unless-stopped
    network_mode: bridge

# Using bind mounts to host directories instead of named volumes
# Directories are created in ./volumes/${VOLUME_PREFIX}/
