services:
  claude-agent:
    image: ${REGISTRY}claude-code-base:latest
    container_name: ${INSTANCE_NAME:-claude-code-agent}
    ports:
      - "${EXTERNAL_PORT:-3010}:3000"
      - "${POSTGRES_PORT:-5432}:5432"
      - "${REDIS_PORT:-6379}:6379"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      # Isolated bind mounts per instance
      - ./volumes/${VOLUME_PREFIX:-claude-code-agent}/workspace:/workspace
      - ./volumes/${VOLUME_PREFIX:-claude-code-agent}/bashhistory:/commandhistory
      # Runtime data - isolated per instance
      - ./volumes/${VOLUME_PREFIX:-claude-code-agent}/config:/home/ubuntu/.claude/runtime
      # Shared Claude authentication files
      - ./volumes/claude-auth/.credentials.json:/home/ubuntu/.claude/.credentials.json
      - ./volumes/claude-auth/.claude.json:/home/ubuntu/.claude/.claude.json
      - ./volumes/claude-auth/settings.json:/home/ubuntu/.claude/settings.json
      # - ./volumes/claude:/home/ubuntu/.claude
    working_dir: /workspace
    user: ubuntu
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096
      - CLAUDE_CONFIG_DIR=/home/ubuntu/.claude
      - POWERLEVEL9K_DISABLE_GITSTATUS=true
      # GitHub authentication token for Git and CLI (set via .env file or environment)
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      # Git configuration (set via .env file or environment)
      - GIT_USERNAME=${GIT_USERNAME:-pitts114}
      - GIT_EMAIL=${GIT_EMAIL:-contact@justinpitts.dev}
      # Docker-in-Docker configuration
      - DOCKER_TLS_CERTDIR=""
      - TZ=America/New_York
    command: bash
    stdin_open: true
    tty: true
    restart: unless-stopped
    network_mode: bridge
    privileged: true
